name: airflow-spark

x-spark-common: &spark-common
  build:
    context: .
    dockerfile: Dockerfile.spark-worker.yml
  environment:
    - SPARK_WORKER_CORES=1
    - SPARK_WORKER_MEMORY=1G
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
  networks:
    - net
  depends_on: &spark-common-depends-on
    spark-master:
      condition: service_healthy


services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark-master.yml
    container_name: spark-master
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/json/ || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - net
    expose:
      - 7077
      - 8080
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker-1:
    <<: *spark-common
    hostname: spark-worker-1
    container_name: spark-worker-1
    depends_on:
      <<: *spark-common-depends-on

  spark-worker-2:
    <<: *spark-common
    hostname: spark-worker-2
    container_name: spark-worker-2
    depends_on:
      <<: *spark-common-depends-on

volumes:
  postgres_data:

networks:
  net:
    driver: bridge